//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgettoAP.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IDBService")]
    public interface IDBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/Connessione", ReplyAction="http://tempuri.org/IDBService/ConnessioneResponse")]
        void Connessione();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/Connessione", ReplyAction="http://tempuri.org/IDBService/ConnessioneResponse")]
        System.Threading.Tasks.Task ConnessioneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/Login", ReplyAction="http://tempuri.org/IDBService/LoginResponse")]
        bool Login(string email, string psw, bool organizzatore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/Login", ReplyAction="http://tempuri.org/IDBService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string email, string psw, bool organizzatore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/InfoUtente", ReplyAction="http://tempuri.org/IDBService/InfoUtenteResponse")]
        Server.Models.UtenteS InfoUtente(string e, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/InfoUtente", ReplyAction="http://tempuri.org/IDBService/InfoUtenteResponse")]
        System.Threading.Tasks.Task<Server.Models.UtenteS> InfoUtenteAsync(string e, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/InfoCeo", ReplyAction="http://tempuri.org/IDBService/InfoCeoResponse")]
        Server.Models.Ceo_organizzazioniS InfoCeo(string e, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/InfoCeo", ReplyAction="http://tempuri.org/IDBService/InfoCeoResponse")]
        System.Threading.Tasks.Task<Server.Models.Ceo_organizzazioniS> InfoCeoAsync(string e, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetNomiOrganizzazioni", ReplyAction="http://tempuri.org/IDBService/GetNomiOrganizzazioniResponse")]
        string GetNomiOrganizzazioni();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetNomiOrganizzazioni", ReplyAction="http://tempuri.org/IDBService/GetNomiOrganizzazioniResponse")]
        System.Threading.Tasks.Task<string> GetNomiOrganizzazioniAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/Registrazione", ReplyAction="http://tempuri.org/IDBService/RegistrazioneResponse")]
        bool Registrazione(string nome, string cognome, string username, string email, string password, bool isOrganizzatore, string nomeOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/Registrazione", ReplyAction="http://tempuri.org/IDBService/RegistrazioneResponse")]
        System.Threading.Tasks.Task<bool> RegistrazioneAsync(string nome, string cognome, string username, string email, string password, bool isOrganizzatore, string nomeOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/EventiDisponibili", ReplyAction="http://tempuri.org/IDBService/EventiDisponibiliResponse")]
        Server.Models.EventoS[] EventiDisponibili();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/EventiDisponibili", ReplyAction="http://tempuri.org/IDBService/EventiDisponibiliResponse")]
        System.Threading.Tasks.Task<Server.Models.EventoS[]> EventiDisponibiliAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetOrganizzazioneFromId", ReplyAction="http://tempuri.org/IDBService/GetOrganizzazioneFromIdResponse")]
        Server.Models.OrganizzazioneS GetOrganizzazioneFromId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetOrganizzazioneFromId", ReplyAction="http://tempuri.org/IDBService/GetOrganizzazioneFromIdResponse")]
        System.Threading.Tasks.Task<Server.Models.OrganizzazioneS> GetOrganizzazioneFromIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetBigliettoFromIdEvento", ReplyAction="http://tempuri.org/IDBService/GetBigliettoFromIdEventoResponse")]
        Server.Models.BigliettoS GetBigliettoFromIdEvento(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetBigliettoFromIdEvento", ReplyAction="http://tempuri.org/IDBService/GetBigliettoFromIdEventoResponse")]
        System.Threading.Tasks.Task<Server.Models.BigliettoS> GetBigliettoFromIdEventoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/AcquistaBiglietto", ReplyAction="http://tempuri.org/IDBService/AcquistaBigliettoResponse")]
        bool AcquistaBiglietto(int idBig, int idUtente, bool isPremium, int idEvento, int numBig);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/AcquistaBiglietto", ReplyAction="http://tempuri.org/IDBService/AcquistaBigliettoResponse")]
        System.Threading.Tasks.Task<bool> AcquistaBigliettoAsync(int idBig, int idUtente, bool isPremium, int idEvento, int numBig);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBServiceChannel : ProgettoAP.ServiceReference.IDBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBServiceClient : System.ServiceModel.ClientBase<ProgettoAP.ServiceReference.IDBService>, ProgettoAP.ServiceReference.IDBService {
        
        public DBServiceClient() {
        }
        
        public DBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Connessione() {
            base.Channel.Connessione();
        }
        
        public System.Threading.Tasks.Task ConnessioneAsync() {
            return base.Channel.ConnessioneAsync();
        }
        
        public bool Login(string email, string psw, bool organizzatore) {
            return base.Channel.Login(email, psw, organizzatore);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string email, string psw, bool organizzatore) {
            return base.Channel.LoginAsync(email, psw, organizzatore);
        }
        
        public Server.Models.UtenteS InfoUtente(string e, string psw) {
            return base.Channel.InfoUtente(e, psw);
        }
        
        public System.Threading.Tasks.Task<Server.Models.UtenteS> InfoUtenteAsync(string e, string psw) {
            return base.Channel.InfoUtenteAsync(e, psw);
        }
        
        public Server.Models.Ceo_organizzazioniS InfoCeo(string e, string psw) {
            return base.Channel.InfoCeo(e, psw);
        }
        
        public System.Threading.Tasks.Task<Server.Models.Ceo_organizzazioniS> InfoCeoAsync(string e, string psw) {
            return base.Channel.InfoCeoAsync(e, psw);
        }
        
        public string GetNomiOrganizzazioni() {
            return base.Channel.GetNomiOrganizzazioni();
        }
        
        public System.Threading.Tasks.Task<string> GetNomiOrganizzazioniAsync() {
            return base.Channel.GetNomiOrganizzazioniAsync();
        }
        
        public bool Registrazione(string nome, string cognome, string username, string email, string password, bool isOrganizzatore, string nomeOrg) {
            return base.Channel.Registrazione(nome, cognome, username, email, password, isOrganizzatore, nomeOrg);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrazioneAsync(string nome, string cognome, string username, string email, string password, bool isOrganizzatore, string nomeOrg) {
            return base.Channel.RegistrazioneAsync(nome, cognome, username, email, password, isOrganizzatore, nomeOrg);
        }
        
        public Server.Models.EventoS[] EventiDisponibili() {
            return base.Channel.EventiDisponibili();
        }
        
        public System.Threading.Tasks.Task<Server.Models.EventoS[]> EventiDisponibiliAsync() {
            return base.Channel.EventiDisponibiliAsync();
        }
        
        public Server.Models.OrganizzazioneS GetOrganizzazioneFromId(int id) {
            return base.Channel.GetOrganizzazioneFromId(id);
        }
        
        public System.Threading.Tasks.Task<Server.Models.OrganizzazioneS> GetOrganizzazioneFromIdAsync(int id) {
            return base.Channel.GetOrganizzazioneFromIdAsync(id);
        }
        
        public Server.Models.BigliettoS GetBigliettoFromIdEvento(int id) {
            return base.Channel.GetBigliettoFromIdEvento(id);
        }
        
        public System.Threading.Tasks.Task<Server.Models.BigliettoS> GetBigliettoFromIdEventoAsync(int id) {
            return base.Channel.GetBigliettoFromIdEventoAsync(id);
        }
        
        public bool AcquistaBiglietto(int idBig, int idUtente, bool isPremium, int idEvento, int numBig) {
            return base.Channel.AcquistaBiglietto(idBig, idUtente, isPremium, idEvento, numBig);
        }
        
        public System.Threading.Tasks.Task<bool> AcquistaBigliettoAsync(int idBig, int idUtente, bool isPremium, int idEvento, int numBig) {
            return base.Channel.AcquistaBigliettoAsync(idBig, idUtente, isPremium, idEvento, numBig);
        }
    }
}
